apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'me.ele.uetool'
    compileSdk versions.compileSdk

    defaultConfig {
        minSdk versions.minSdk
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
    }

    publishing {
        singleVariant('release')
    }
}

dependencies {
    compileOnly project(':uetool-base')
//      api "me.ele:uetool-base:${versions.release}"
    implementation "com.jakewharton.scalpel:scalpel:${versions.scalpel}"
    implementation ("com.github.bmelnychuk:atv:${versions.treeView}") {
        exclude group: 'com.android.support', module: 'appcompat-v7'
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
            }
        }
    }
}
