apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'me.ele.uetool'
    compileSdk versions.compileSdk
    enableKotlin = false

    defaultConfig {
        minSdk versions.minSdk
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    publishing {
        singleVariant('release')
    }
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
            }
        }
    }
}
