[versions]
agp = "8.13.0"
kotlin = "2.0.21"
minSdk = "21"
targetSdk = "35"
compileSdk = "35"

appcompat = "1.7.1"
annotation = "1.10.0"
core = "1.9.0"
composeUi = "1.11.2"
fragment = "1.8.9"
fresco = "3.6.0"
leakCanary = "2.14"
lifecycle = "2.9.0"
material = "1.13.0"
scalpel = "1.1.2"
treeView = "1.2.9"
freeReflection = "3.1.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-core = { module = "androidx.core:core", version.ref = "core" }
androidx-fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
facebook-fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
facebook-fresco-animated-gif = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
free-reflection = { module = "com.github.tiann:FreeReflection", version.ref = "freeReflection" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakCanary" }
material = { module = "com.google.android.material:material", version.ref = "material" }
scalpel = { module = "com.jakewharton.scalpel:scalpel", version.ref = "scalpel" }
treeview = { module = "com.github.bmelnychuk:atv", version.ref = "treeView" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
