apply plugin: 'com.android.application'

android {
    namespace 'me.ele.uetool.sample'
    compileSdk versions.compileSdk

    signingConfigs {
        release {
            storeFile file("../uetool.jks")
            keyAlias 'uetool'
            keyPassword 'uetool'
            storePassword 'uetool'
        }
    }

    defaultConfig {
        applicationId "me.ele.uetool.sample"
        minSdk versions.minSdk
        targetSdk versions.targetSdk
        multiDexEnabled true
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:${versions.appcompat}"
    implementation "androidx.constraintlayout:constraintlayout:${versions.constraint}"
    implementation "androidx.coordinatorlayout:coordinatorlayout:${versions.coordinator}"
    implementation "androidx.lifecycle:lifecycle-viewmodel:${versions.lifecycle}"
    implementation "com.google.android.material:material:${versions.material}"
    implementation "com.facebook.fresco:fresco:${versions.fresco}"
    implementation "com.facebook.fresco:animated-gif:${versions.fresco}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    debugImplementation "com.squareup.leakcanary:leakcanary-android:${versions.leakCanary}"

    debugImplementation project(':uetool')
    debugImplementation project(':uetool-fresco')
    debugImplementation project(':uetool-base')
    debugImplementation project(':uetool-compose')
    releaseImplementation project(':uetool-no-op')
//  debugImplementation "me.ele:uetool:${versions.release}"
//  debugImplementation "me.ele:uetool-fresco:${versions.release}"
//  releaseImplementation "me.ele:uetool-no-op:${versions.release}"

    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
}
