apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'me.ele.uetool.base'
    compileSdk versions.compileSdk
    enableKotlin = false

    defaultConfig {
        minSdk versions.minSdk
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
    }

    publishing {
        singleVariant('release')
    }
}

dependencies {
    api "androidx.annotation:annotation:${versions.annotation}"
    api "androidx.appcompat:appcompat:${versions.appcompat}"
    api "androidx.core:core:${versions.core}"
    api "androidx.fragment:fragment:${versions.fragment}"
    api "androidx.recyclerview:recyclerview:${versions.recyclerview}"
    api "androidx.vectordrawable:vectordrawable:${versions.vectorDrawable}"
    implementation "com.github.tiann:FreeReflection:3.1.0"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
            }
        }
    }
}
