apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'me.ele.uetool.fresco'
    compileSdk versions.compileSdk

    defaultConfig {
        minSdk versions.minSdk
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    lint {
        abortOnError false
    }

    publishing {
        singleVariant('release')
    }
}

dependencies {
    compileOnly project(':uetool-base')
//      implementation "me.ele:uetool-base:${versions.release}"
    compileOnly "com.facebook.fresco:fresco:${versions.fresco}"
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
            }
        }
    }
}
